const https = require('https');
const axios = require('axios');
const { Pool, Client } = require('pg');

const pool = new Pool({
    user: 'postgres',
    host: 'localhost',
    database: 'fnde',
    password: 'admin',
    port: 5432
});

var objetos = [
    { codigo: 410010,
        nome: "Abatiá" },
        { codigo: 410020,
        nome: "Adrianópolis" },
        { codigo: 410030,
        nome: "Agudos do Sul" },
        { codigo: 410040,
        nome: "Almirante Tamandaré" },
        { codigo: 410045,
        nome: "Altamira do Paraná" },
        { codigo: 412862,
        nome: "Alto Paraíso" },
        { codigo: 410060,
        nome: "Alto Paraná" },
        { codigo: 410070,
        nome: "Alto Piquiri" },
        { codigo: 410050,
        nome: "Altônia" },
        { codigo: 410080,
        nome: "Alvorada do Sul" },
        { codigo: 410090,
        nome: "Amaporã" },
        { codigo: 410100,
        nome: "Ampére" },
        { codigo: 410105,
        nome: "Anahy" },
        { codigo: 410110,
        nome: "Andirá" },
        { codigo: 410115,
        nome: "Ângulo" },
        { codigo: 410120,
        nome: "Antonina" },
        { codigo: 410130,
        nome: "Antônio Olinto" },
        { codigo: 410140,
        nome: "Apucarana" },
        { codigo: 410150,
        nome: "Arapongas" },
        { codigo: 410160,
        nome: "Arapoti" },
        { codigo: 410165,
        nome: "Arapuã" },
        { codigo: 410170,
        nome: "Araruna" },
        { codigo: 410180,
        nome: "Araucária" },
        { codigo: 410185,
        nome: "Ariranha do Ivaí" },
        { codigo: 410190,
        nome: "Assaí" },
        { codigo: 410200,
        nome: "Assis Chateaubriand" },
        { codigo: 410210,
        nome: "Astorga" },
        { codigo: 410220,
        nome: "Atalaia" },
        { codigo: 410230,
        nome: "Balsa Nova" },
        { codigo: 410240,
        nome: "Bandeirantes" },
        { codigo: 410250,
        nome: "Barbosa Ferraz" },
        { codigo: 410270,
        nome: "Barra do Jacaré" },
        { codigo: 410260,
        nome: "Barracão" },
        { codigo: 410275,
        nome: "Bela Vista da Caroba" },
        { codigo: 410280,
        nome: "Bela Vista do Paraíso" },
        { codigo: 410290,
        nome: "Bituruna" },
        { codigo: 410300,
        nome: "Boa Esperança" },
        { codigo: 410302,
        nome: "Boa Esperança do Iguaçu" },
        { codigo: 410304,
        nome: "Boa Ventura de São Roque" },
        { codigo: 410305,
        nome: "Boa Vista da Aparecida" },
        { codigo: 410310,
        nome: "Bocaiúva do Sul" },
        { codigo: 410315,
        nome: "Bom Jesus do Sul" },
        { codigo: 410320,
        nome: "Bom Sucesso" },
        { codigo: 410322,
        nome: "Bom Sucesso do Sul" },
        { codigo: 410330,
        nome: "Borrazópolis" },
        { codigo: 410335,
        nome: "Braganey" },
        { codigo: 410337,
        nome: "Brasilândia do Sul" },
        { codigo: 410340,
        nome: "Cafeara" },
        { codigo: 410345,
        nome: "Cafelândia" },
        { codigo: 410347,
        nome: "Cafezal do Sul" },
        { codigo: 410350,
        nome: "Califórnia" },
        { codigo: 410360,
        nome: "Cambará" },
        { codigo: 410370,
        nome: "Cambé" },
        { codigo: 410380,
        nome: "Cambira" },
        { codigo: 410390,
        nome: "Campina da Lagoa" },
        { codigo: 410395,
        nome: "Campina do Simão" },
        { codigo: 410400,
        nome: "Campina Grande do Sul" },
        { codigo: 410405,
        nome: "Campo Bonito" },
        { codigo: 410410,
        nome: "Campo do Tenente" },
        { codigo: 410420,
        nome: "Campo Largo" },
        { codigo: 410425,
        nome: "Campo Magro" },
        { codigo: 410430,
        nome: "Campo Mourão" },
        { codigo: 410440,
        nome: "Cândido de Abreu" },
        { codigo: 410442,
        nome: "Candói" },
        { codigo: 410445,
        nome: "Cantagalo" },
        { codigo: 410450,
        nome: "Capanema" },
        { codigo: 410460,
        nome: "Capitão Leônidas Marques" },
        { codigo: 410465,
        nome: "Carambeí" },
        { codigo: 410470,
        nome: "Carlópolis" },
        { codigo: 410480,
        nome: "Cascavel" },
        { codigo: 410490,
        nome: "Castro" },
        { codigo: 410500,
        nome: "Catanduvas" },
        { codigo: 410510,
        nome: "Centenário do Sul" },
        { codigo: 410520,
        nome: "Cerro Azul" },
        { codigo: 410530,
        nome: "Céu Azul" },
        { codigo: 410540,
        nome: "Chopinzinho" },
        { codigo: 410550,
        nome: "Cianorte" },
        { codigo: 410560,
        nome: "Cidade Gaúcha" },
        { codigo: 410570,
        nome: "Clevelândia" },
        { codigo: 410580,
        nome: "Colombo" },
        { codigo: 410590,
        nome: "Colorado" },
        { codigo: 410600,
        nome: "Congonhinhas" },
        { codigo: 410610,
        nome: "Conselheiro Mairinck" },
        { codigo: 410620,
        nome: "Contenda" },
        { codigo: 410630,
        nome: "Corbélia" },
        { codigo: 410640,
        nome: "Cornélio Procópio" },
        { codigo: 410645,
        nome: "Coronel Domingos Soares" },
        { codigo: 410650,
        nome: "Coronel Vivida" },
        { codigo: 410655,
        nome: "Corumbataí do Sul" },
        { codigo: 410680,
        nome: "Cruz Machado" },
        { codigo: 410657,
        nome: "Cruzeiro do Iguaçu" },
        { codigo: 410660,
        nome: "Cruzeiro do Oeste" },
        { codigo: 410670,
        nome: "Cruzeiro do Sul" },
        { codigo: 410685,
        nome: "Cruzmaltina" },
        { codigo: 410690,
        nome: "Curitiba" },
        { codigo: 410700,
        nome: "Curiúva" },
        { codigo: 410710,
        nome: "Diamante do Norte" },
        { codigo: 410712,
        nome: "Diamante do Sul" },
        { codigo: 410715,
        nome: "Diamante DOeste" },
        { codigo: 410720,
        nome: "Dois Vizinhos" },
        { codigo: 410725,
        nome: "Douradina" },
        { codigo: 410730,
        nome: "Doutor Camargo" },
        { codigo: 412863,
        nome: "Doutor Ulysses" },
        { codigo: 410740,
        nome: "Enéas Marques" },
        { codigo: 410750,
        nome: "Engenheiro Beltrão" },
        { codigo: 410753,
        nome: "Entre Rios do Oeste" },
        { codigo: 410752,
        nome: "Esperança Nova" },
        { codigo: 410754,
        nome: "Espigão Alto do Iguaçu" },
        { codigo: 410755,
        nome: "Farol" },
        { codigo: 410760,
        nome: "Faxinal" },
        { codigo: 410765,
        nome: "Fazenda Rio Grande" },
        { codigo: 410770,
        nome: "Fênix" },
        { codigo: 410773,
        nome: "Fernandes Pinheiro" },
        { codigo: 410775,
        nome: "Figueira" },
        { codigo: 410785,
        nome: "Flor da Serra do Sul" },
        { codigo: 410780,
        nome: "Floraí" },
        { codigo: 410790,
        nome: "Floresta" },
        { codigo: 410800,
        nome: "Florestópolis" },
        { codigo: 410810,
        nome: "Flórida" },
        { codigo: 410820,
        nome: "Formosa do Oeste" },
        { codigo: 410830,
        nome: "Foz do Iguaçu" },
        { codigo: 410845,
        nome: "Foz do Jordão" },
        { codigo: 410832,
        nome: "Francisco Alves" },
        { codigo: 410840,
        nome: "Francisco Beltrão" },
        { codigo: 410850,
        nome: "General Carneiro" },
        { codigo: 410855,
        nome: "Godoy Moreira" },
        { codigo: 410860,
        nome: "Goioerê" },
        { codigo: 410865,
        nome: "Goioxim" },
        { codigo: 410870,
        nome: "Grandes Rios" },
        { codigo: 410880,
        nome: "Guaíra" },
        { codigo: 410890,
        nome: "Guairaçá" },
        { codigo: 410895,
        nome: "Guamiranga" },
        { codigo: 410900,
        nome: "Guapirama" },
        { codigo: 410910,
        nome: "Guaporema" },
        { codigo: 410920,
        nome: "Guaraci" },
        { codigo: 410930,
        nome: "Guaraniaçu" },
        { codigo: 410940,
        nome: "Guarapuava" },
        { codigo: 410950,
        nome: "Guaraqueçaba" },
        { codigo: 410960,
        nome: "Guaratuba" },
        { codigo: 410965,
        nome: "Honório Serpa" },
        { codigo: 410970,
        nome: "Ibaiti" },
        { codigo: 410975,
        nome: "Ibema" },
        { codigo: 410980,
        nome: "Ibiporã" },
        { codigo: 410990,
        nome: "Icaraíma" },
        { codigo: 411000,
        nome: "Iguaraçu" },
        { codigo: 411005,
        nome: "Iguatu" },
        { codigo: 411007,
        nome: "Imbaú" },
        { codigo: 411010,
        nome: "Imbituva" },
        { codigo: 411020,
        nome: "Inácio Martins" },
        { codigo: 411030,
        nome: "Inajá" },
        { codigo: 411040,
        nome: "Indianópolis" },
        { codigo: 411050,
        nome: "Ipiranga" },
        { codigo: 411060,
        nome: "Iporã" },
        { codigo: 411065,
        nome: "Iracema do Oeste" },
        { codigo: 411070,
        nome: "Irati" },
        { codigo: 411080,
        nome: "Iretama" },
        { codigo: 411090,
        nome: "Itaguajé" },
        { codigo: 411095,
        nome: "Itaipulândia" },
        { codigo: 411100,
        nome: "Itambaracá" },
        { codigo: 411110,
        nome: "Itambé" },
        { codigo: 411120,
        nome: "Itapejara dOeste" },
        { codigo: 411125,
        nome: "Itaperuçu" },
        { codigo: 411130,
        nome: "Itaúna do Sul" },
        { codigo: 411140,
        nome: "Ivaí" },
        { codigo: 411150,
        nome: "Ivaiporã" },
        { codigo: 411155,
        nome: "Ivaté" },
        { codigo: 411160,
        nome: "Ivatuba" },
        { codigo: 411170,
        nome: "Jaboti" },
        { codigo: 411180,
        nome: "Jacarezinho" },
        { codigo: 411190,
        nome: "Jaguapitã" },
        { codigo: 411200,
        nome: "Jaguariaíva" },
        { codigo: 411210,
        nome: "Jandaia do Sul" },
        { codigo: 411220,
        nome: "Janiópolis" },
        { codigo: 411230,
        nome: "Japira" },
        { codigo: 411240,
        nome: "Japurá" },
        { codigo: 411250,
        nome: "Jardim Alegre" },
        { codigo: 411260,
        nome: "Jardim Olinda" },
        { codigo: 411270,
        nome: "Jataizinho" },
        { codigo: 411275,
        nome: "Jesuítas" },
        { codigo: 411280,
        nome: "Joaquim Távora" },
        { codigo: 411290,
        nome: "Jundiaí do Sul" },
        { codigo: 411295,
        nome: "Juranda" },
        { codigo: 411300,
        nome: "Jussara" },
        { codigo: 411310,
        nome: "Kaloré" },
        { codigo: 411320,
        nome: "Lapa" },
        { codigo: 411325,
        nome: "Laranjal" },
        { codigo: 411330,
        nome: "Laranjeiras do Sul" },
        { codigo: 411340,
        nome: "Leópolis" },
        { codigo: 411342,
        nome: "Lidianópolis" },
        { codigo: 411345,
        nome: "Lindoeste" },
        { codigo: 411350,
        nome: "Loanda" },
        { codigo: 411360,
        nome: "Lobato" },
        { codigo: 411370,
        nome: "Londrina" },
        { codigo: 411373,
        nome: "Luiziana" },
        { codigo: 411375,
        nome: "Lunardelli" },
        { codigo: 411380,
        nome: "Lupionópolis" },
        { codigo: 411390,
        nome: "Mallet" },
        { codigo: 411400,
        nome: "Mamborê" },
        { codigo: 411410,
        nome: "Mandaguaçu" },
        { codigo: 411420,
        nome: "Mandaguari" },
        { codigo: 411430,
        nome: "Mandirituba" },
        { codigo: 411435,
        nome: "Manfrinópolis" },
        { codigo: 411440,
        nome: "Mangueirinha" },
        { codigo: 411450,
        nome: "Manoel Ribas" },
        { codigo: 411460,
        nome: "Marechal Cândido Rondon" },
        { codigo: 411470,
        nome: "Maria Helena" },
        { codigo: 411480,
        nome: "Marialva" },
        { codigo: 411490,
        nome: "Marilândia do Sul" },
        { codigo: 411500,
        nome: "Marilena" },
        { codigo: 411510,
        nome: "Mariluz" },
        { codigo: 411520,
        nome: "Maringá" },
        { codigo: 411530,
        nome: "Mariópolis" },
        { codigo: 411535,
        nome: "Maripá" },
        { codigo: 411540,
        nome: "Marmeleiro" },
        { codigo: 411545,
        nome: "Marquinho" },
        { codigo: 411550,
        nome: "Marumbi" },
        { codigo: 411560,
        nome: "Matelândia" },
        { codigo: 411570,
        nome: "Matinhos" },
        { codigo: 411573,
        nome: "Mato Rico" },
        { codigo: 411575,
        nome: "Mauá da Serra" },
        { codigo: 411580,
        nome: "Medianeira" },
        { codigo: 411585,
        nome: "Mercedes" },
        { codigo: 411590,
        nome: "Mirador" },
        { codigo: 411600,
        nome: "Miraselva" },
        { codigo: 411605,
        nome: "Missal" },
        { codigo: 411610,
        nome: "Moreira Sales" },
        { codigo: 411620,
        nome: "Morretes" },
        { codigo: 411630,
        nome: "Munhoz de Melo" },
        { codigo: 411640,
        nome: "Nossa Senhora das Graças" },
        { codigo: 411650,
        nome: "Nova Aliança do Ivaí" },
        { codigo: 411660,
        nome: "Nova América da Colina" },
        { codigo: 411670,
        nome: "Nova Aurora" },
        { codigo: 411680,
        nome: "Nova Cantu" },
        { codigo: 411690,
        nome: "Nova Esperança" },
        { codigo: 411695,
        nome: "Nova Esperança do Sudoeste" },
        { codigo: 411700,
        nome: "Nova Fátima" },
        { codigo: 411705,
        nome: "Nova Laranjeiras" },
        { codigo: 411710,
        nome: "Nova Londrina" },
        { codigo: 411720,
        nome: "Nova Olímpia" },
        { codigo: 411725,
        nome: "Nova Prata do Iguaçu" },
        { codigo: 411721,
        nome: "Nova Santa Bárbara" },
        { codigo: 411722,
        nome: "Nova Santa Rosa" },
        { codigo: 411727,
        nome: "Nova Tebas" },
        { codigo: 411729,
        nome: "Novo Itacolomi" },
        { codigo: 411730,
        nome: "Ortigueira" },
        { codigo: 411740,
        nome: "Ourizona" },
        { codigo: 411745,
        nome: "Ouro Verde do Oeste" },
        { codigo: 411750,
        nome: "Paiçandu" },
        { codigo: 411760,
        nome: "Palmas" },
        { codigo: 411770,
        nome: "Palmeira" },
        { codigo: 411780,
        nome: "Palmital" },
        { codigo: 411790,
        nome: "Palotina" },
        { codigo: 411800,
        nome: "Paraíso do Norte" },
        { codigo: 411810,
        nome: "Paranacity" },
        { codigo: 411820,
        nome: "Paranaguá" },
        { codigo: 411830,
        nome: "Paranapoema" },
        { codigo: 411840,
        nome: "Paranavaí" },
        { codigo: 411845,
        nome: "Pato Bragado" },
        { codigo: 411850,
        nome: "Pato Branco" },
        { codigo: 411860,
        nome: "Paula Freitas" },
        { codigo: 411870,
        nome: "Paulo Frontin" },
        { codigo: 411880,
        nome: "Peabiru" },
        { codigo: 411885,
        nome: "Perobal" },
        { codigo: 411890,
        nome: "Pérola" },
        { codigo: 411900,
        nome: "Pérola dOeste" },
        { codigo: 411910,
        nome: "Piên" },
        { codigo: 411915,
        nome: "Pinhais" },
        { codigo: 411925,
        nome: "Pinhal de São Bento" },
        { codigo: 411920,
        nome: "Pinhalão" },
        { codigo: 411930,
        nome: "Pinhão" },
        { codigo: 411940,
        nome: "Piraí do Sul" },
        { codigo: 411950,
        nome: "Piraquara" },
        { codigo: 411960,
        nome: "Pitanga" },
        { codigo: 411965,
        nome: "Pitangueiras" },
        { codigo: 411970,
        nome: "Planaltina do Paraná" },
        { codigo: 411980,
        nome: "Planalto" },
        { codigo: 411990,
        nome: "Ponta Grossa" },
        { codigo: 411995,
        nome: "Pontal do Paraná" },
        { codigo: 412000,
        nome: "Porecatu" },
        { codigo: 412010,
        nome: "Porto Amazonas" },
        { codigo: 412015,
        nome: "Porto Barreiro" },
        { codigo: 412020,
        nome: "Porto Rico" },
        { codigo: 412030,
        nome: "Porto Vitória" },
        { codigo: 412033,
        nome: "Prado Ferreira" },
        { codigo: 412035,
        nome: "Pranchita" },
        { codigo: 412040,
        nome: "Presidente Castelo Branco" },
        { codigo: 412050,
        nome: "Primeiro de Maio" },
        { codigo: 412060,
        nome: "Prudentópolis" },
        { codigo: 412065,
        nome: "Quarto Centenário" },
        { codigo: 412070,
        nome: "Quatiguá" },
        { codigo: 412080,
        nome: "Quatro Barras" },
        { codigo: 412085,
        nome: "Quatro Pontes" },
        { codigo: 412090,
        nome: "Quedas do Iguaçu" },
        { codigo: 412100,
        nome: "Querência do Norte" },
        { codigo: 412110,
        nome: "Quinta do Sol" },
        { codigo: 412120,
        nome: "Quitandinha" },
        { codigo: 412125,
        nome: "Ramilândia" },
        { codigo: 412130,
        nome: "Rancho Alegre" },
        { codigo: 412135,
        nome: "Rancho Alegre DOeste" },
        { codigo: 412140,
        nome: "Realeza" },
        { codigo: 412150,
        nome: "Rebouças" },
        { codigo: 412160,
        nome: "Renascença" },
        { codigo: 412170,
        nome: "Reserva" },
        { codigo: 412175,
        nome: "Reserva do Iguaçu" },
        { codigo: 412180,
        nome: "Ribeirão Claro" },
        { codigo: 412190,
        nome: "Ribeirão do Pinhal" },
        { codigo: 412200,
        nome: "Rio Azul" },
        { codigo: 412210,
        nome: "Rio Bom" },
        { codigo: 412215,
        nome: "Rio Bonito do Iguaçu" },
        { codigo: 412217,
        nome: "Rio Branco do Ivaí" },
        { codigo: 412220,
        nome: "Rio Branco do Sul" },
        { codigo: 412230,
        nome: "Rio Negro" },
        { codigo: 412240,
        nome: "Rolândia" },
        { codigo: 412250,
        nome: "Roncador" },
        { codigo: 412260,
        nome: "Rondon" },
        { codigo: 412265,
        nome: "Rosário do Ivaí" },
        { codigo: 412270,
        nome: "Sabáudia" },
        { codigo: 412280,
        nome: "Salgado Filho" },
        { codigo: 412290,
        nome: "Salto do Itararé" },
        { codigo: 412300,
        nome: "Salto do Lontra" },
        { codigo: 412310,
        nome: "Santa Amélia" },
        { codigo: 412320,
        nome: "Santa Cecília do Pavão" },
        { codigo: 412330,
        nome: "Santa Cruz de Monte Castelo" },
        { codigo: 412340,
        nome: "Santa Fé" },
        { codigo: 412350,
        nome: "Santa Helena" },
        { codigo: 412360,
        nome: "Santa Inês" },
        { codigo: 412370,
        nome: "Santa Isabel do Ivaí" },
        { codigo: 412380,
        nome: "Santa Izabel do Oeste" },
        { codigo: 412382,
        nome: "Santa Lúcia" },
        { codigo: 412385,
        nome: "Santa Maria do Oeste" },
        { codigo: 412390,
        nome: "Santa Mariana" },
        { codigo: 412395,
        nome: "Santa Mônica" },
        { codigo: 412402,
        nome: "Santa Tereza do Oeste" },
        { codigo: 412405,
        nome: "Santa Terezinha de Itaipu" },
        { codigo: 412400,
        nome: "Santana do Itararé" },
        { codigo: 412410,
        nome: "Santo Antônio da Platina" },
        { codigo: 412420,
        nome: "Santo Antônio do Caiuá" },
        { codigo: 412430,
        nome: "Santo Antônio do Paraíso" },
        { codigo: 412440,
        nome: "Santo Antônio do Sudoeste" },
        { codigo: 412450,
        nome: "Santo Inácio" },
        { codigo: 412460,
        nome: "São Carlos do Ivaí" },
        { codigo: 412470,
        nome: "São Jerônimo da Serra" },
        { codigo: 412480,
        nome: "São João" },
        { codigo: 412490,
        nome: "São João do Caiuá" },
        { codigo: 412500,
        nome: "São João do Ivaí" },
        { codigo: 412510,
        nome: "São João do Triunfo" },
        { codigo: 412530,
        nome: "São Jorge do Ivaí" },
        { codigo: 412535,
        nome: "São Jorge do Patrocínio" },
        { codigo: 412520,
        nome: "São Jorge dOeste" },
        { codigo: 412540,
        nome: "São José da Boa Vista" },
        { codigo: 412545,
        nome: "São José das Palmeiras" },
        { codigo: 412550,
        nome: "São José dos Pinhais" },
        { codigo: 412555,
        nome: "São Manoel do Paraná" },
        { codigo: 412560,
        nome: "São Mateus do Sul" },
        { codigo: 412570,
        nome: "São Miguel do Iguaçu" },
        { codigo: 412575,
        nome: "São Pedro do Iguaçu" },
        { codigo: 412580,
        nome: "São Pedro do Ivaí" },
        { codigo: 412590,
        nome: "São Pedro do Paraná" },
        { codigo: 412600,
        nome: "São Sebastião da Amoreira" },
        { codigo: 412610,
        nome: "São Tomé" },
        { codigo: 412620,
        nome: "Sapopema" },
        { codigo: 412625,
        nome: "Sarandi" },
        { codigo: 412627,
        nome: "Saudade do Iguaçu" },
        { codigo: 412630,
        nome: "Sengés" },
        { codigo: 412635,
        nome: "Serranópolis do Iguaçu" },
        { codigo: 412640,
        nome: "Sertaneja" },
        { codigo: 412650,
        nome: "Sertanópolis" },
        { codigo: 412660,
        nome: "Siqueira Campos" },
        { codigo: 412665,
        nome: "Sulina" },
        { codigo: 412667,
        nome: "Tamarana" },
        { codigo: 412670,
        nome: "Tamboara" },
        { codigo: 412680,
        nome: "Tapejara" },
        { codigo: 412690,
        nome: "Tapira" },
        { codigo: 412700,
        nome: "Teixeira Soares" },
        { codigo: 412710,
        nome: "Telêmaco Borba" },
        { codigo: 412720,
        nome: "Terra Boa" },
        { codigo: 412730,
        nome: "Terra Rica" },
        { codigo: 412740,
        nome: "Terra Roxa" },
        { codigo: 412750,
        nome: "Tibagi" },
        { codigo: 412760,
        nome: "Tijucas do Sul" },
        { codigo: 412770,
        nome: "Toledo" },
        { codigo: 412780,
        nome: "Tomazina" },
        { codigo: 412785,
        nome: "Três Barras do Paraná" },
        { codigo: 412788,
        nome: "Tunas do Paraná" },
        { codigo: 412790,
        nome: "Tuneiras do Oeste" },
        { codigo: 412795,
        nome: "Tupãssi" },
        { codigo: 412796,
        nome: "Turvo" },
        { codigo: 412800,
        nome: "Ubiratã" },
        { codigo: 412810,
        nome: "Umuarama" },
        { codigo: 412820,
        nome: "União da Vitória" },
        { codigo: 412830,
        nome: "Uniflor" },
        { codigo: 412840,
        nome: "Uraí" },
        { codigo: 412853,
        nome: "Ventania" },
        { codigo: 412855,
        nome: "Vera Cruz do Oeste" },
        { codigo: 412860,
        nome: "Verê" },
        { codigo: 412865,
        nome: "Virmond" },
        { codigo: 412870,
        nome: "Vitorino" },
        { codigo: 412850,
        nome: "Wenceslau Braz" },
        { codigo: 412880,
        nome: "Xambrê" }
]

requestFnde();

async function requestFnde() {
    for(var ano = 2017; ano < 2020; ano++) {
        // var ano = 2011;
        for( var i=0; i < 399; i++) {
            await axios.get('https://www.fnde.gov.br/siope/dadosInformadosMunicipio.do?acao=pesquisar&pag=result&anos=' + ano.toString() + '&periodos=6&cod_uf=41&municipios=' + objetos[i].codigo + '&admin=3&planilhas=125&descricaoItem=*+Consolidado+de+Despesa&descricaodoItem=*+Consolidado+de+Receita&nivel=')
            .then(response => {
                let data = response.data;
                var dataSubstring = data.substring(data.indexOf("<td colspan='2'><strong>DESPESA TOTAL (Inclui Inativos)</strong></td>"));
                var dataSubstring = dataSubstring.substring(0, dataSubstring.indexOf("</tr>"));
                for( var j = 0; j < 3; j++) {
                    dataSubstring = dataSubstring.substring(dataSubstring.indexOf("</td>") + 5);
                }
                dataSubstring = dataSubstring.substring(dataSubstring.indexOf("<div"), dataSubstring.indexOf("</td>"));
                dataSubstring = dataSubstring.substring(28,dataSubstring.indexOf("</"));
                dataSubstring = dataSubstring.replace('.', '');
                dataSubstring = dataSubstring.replace('.', '');
                dataSubstring = dataSubstring.replace('.', '');
                dataSubstring = dataSubstring.replace('.', '');
                valor = dataSubstring.replace(',', '.')
                if(valor == ''){
                    valor = 0.00;
                }
                pool.query("INSERT INTO fnde(codigomunicipio, municipio, ano, valor) VALUES (' "+ objetos[i].codigo + 
                            "','" + objetos[i].nome + "','" + ano + "','" + valor + "')");
            }).catch(error => {
                console.log(error);
            })
        }
    }
}